baseurl = "http://www.rbrband.in/"
languageCode = "en-us"
theme = "prologue"
title = "RBRband Records"
[params]
copyright = "RBRband Records"
description = "Vocalist, Sound Engineer"
name = "Prasang Misra"
individual_gigs_description = "'Versatile' just like a RBRband, we are multipurpose.  Be it a Sunday brunch, a wedding party, a pub, we've done it all."

individual_shows_description = "Janta Ki Vishesh Maang is a popular FB live show hosted by Prasang where people can send in their song requests and they are covered live on Facebook. With 1000+ views on every single video, it is one of the most interesting and enticing projects undertaken by RBRband records."

individual_sessions_description = "Not limited to covers or mash-ups, we bring to you our original freshly brewed music from a highly professional RBRband Studio. From soft romantic to the power ballads, we've got'em all"

collab_gigs_description = "Co-creation, Collaboration, Communication and Catalysing Music are some of our beliefs. Do you believe in growing together too? Get in touch"
collab_shows_description = ""
collab_sessions_description = ""

services_singing_description = ""
services_music_production_description = ""
services_other_description = ""

[[params.portfolio1]]
alt = ""
source = "img/pic02.jpg"
title = "Safar Cover"
url = "#"
[[params.portfolio1]]
alt = ""
source = "img/pic03.jpg"
title = "Rhoncus Semper"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic04.jpg"
title = "Magna Nullam"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic05.jpg"
title = "Natoque Vitae"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic06.jpg"
title = "Dolor Penatibus"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic07.jpg"
title = "Orci Convallis"
url = "#"






[[params.social]]
icon = "twitter"
link = "https://twitter.com/prasangmisra"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "https://www.facebook.com/rbrbandrecords"
medium = "facebook"
[[params.social]]
icon = "youtube"
link = "https://www.youtube.com/channel/UCmS5QyYmLb1qLZAs_Kg97Bg"
medium = "youtube"
[[params.social]]
icon = "soundcloud"
link = "https://soundcloud.com/prasangmisra"
medium = "soundcloud"
[[params.social]]
icon = "envelope"
link = "#"
medium = "email"




[[params.individual.gigs]]
title = "Enna Sona"
url = "https://www.youtube.com/embed/IrfZ3fC5NWo"
id = "IrfZ3fC5NWo"
imageurl = ""
[[params.individual.gigs]]
title = "Gulaabi Aakhein"
url = "https://www.youtube.com/embed/0jK6wxLgiIc"
id = "0jK6wxLgiIc"
imageurl = ""
[[params.individual.gigs]]
title = "Haareya"
url = "https://www.youtube.com/embed/Y8pIj4kIheI"
id = "Y8pIj4kIheI"
imageurl = ""
[[params.individual.gigs]]
title = "Fitoor"
url = "https://www.youtube.com/embed/J6GacoGTGDA"
id = "J6GacoGTGDA"
imageurl = ""
[[params.individual.gigs]]
title = "Love Mashup"
url = "https://www.youtube.com/embed/uHuB-meZnC8"
imageurl = ""
id = "uHuB-meZnC8"

[[params.collab.gigs]]
title = "Love Mashup"
url = "https://www.youtube.com/embed/uHuB-meZnC8"
imageurl = ""
id = "uHuB-meZnC8"



[[params.individual.shows.jkvm]]
title = "Episode 50"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1054655078007088%2F&show_text=0&width=180"


[[params.individual.shows.jkvm]]
title = "Episode 49"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1053558484783414%2F&show_text=0&width=180"


[[params.individual.shows.jkvm]]
title = "Episode 48"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1052509001555029%2F&show_text=0&width=180"

[[params.individual.shows.jkvm]]
title = "Episode 47"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1050884941717435%2F&show_text=0&width=267"


[[params.individual.shows.jkvm]]
title = "Episode 46"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1049851335154129%2F&show_text=0&width=267"








[[params.individual.sessions]]
title = "9 Se 12 Power Ballad"
url = "https://www.youtube.com/embed/ft-_F_kGAtA"
id="ft-_F_kGAtA"
[[params.individual.sessions]]
title = "Safar Cover"
url = "https://www.youtube.com/embed/1SA6c7UCcr0"
id="1SA6c7UCcr0"
[[params.individual.sessions]]
title = "Hawaayein Whistle Mashup"
url = "https://www.youtube.com/embed/lYK1tC-xJbk"
id="lYK1tC-xJbk"
[[params.individual.sessions]]
title = "O Maajhi Re Cover"
url = "https://www.youtube.com/embed/PdI-lLu17UU"
id="PdI-lLu17UU"







[[params.gallery.pictures]]
title = "BMC"
url1 = "https://photos.google.com/share/AF1QipOLKYqzKzThxkqVDKEAqyeLjgb_WBiELgu5IFbj5UXDIqOC_pOMaPgyzPFCRyKDCg?key=OWpDNzh4OVc2QTNBYTRoU1NBbXJTQ1JabjJ1NmJ3&source=ctrlq.org"
url = "https://lh3.googleusercontent.com/dvMewqqRxav1-gSmTe8wqPjKzOkbRCkSThXGKYzbs2Q_esXxuYrukj6bD1TZoVPPjm57LlCpIzP3NQ742IB3t63UNh0CgjybZm3ILOzGrb508Uv0dW9Qwf0rEbyukAKVD1AibtRqF20=w2400"

[[params.gallery.videos]]
title = "Maayi Ni Meriye"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1053558484783414%2F&show_text=0&width=194"

[[params.gallery.videos]]
title = "Maayi Ni Meriye1"
url = "https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Frbrbandrecords%2Fvideos%2F1053558484783414%2F&show_text=0&width=194"












[[params.services]]
name = "Performance"
icon = "img/microphone.png"
description = "With plethora of experience in Solo and band gigs at cafes, pubs and corporate event we understand the pulse of the crowd."
	
	[params.services.performance1]
	name=""
   	[[params.services.performance1.list]]
    name="Solo Singing - 1 pc"
   	[[params.services.performance1.list]]
   	name="Singer and guitarist - 2 pc"
   	[[params.services.performance1.list]]
   	name="Singer and MIDI piano - 1 pc" 
	  [[params.services.performance1.list]]
   	name="Corporate event Singing"
 		[[params.services.performance1.list]]
   	name="Bollywood"
 		[[params.services.performance1.list]]
 		name="Soft Romantic"
   




[[params.services]]
name = "Music Production"
icon = "/img/equalizer.png"
description = "With ever evolving Music tech it's tough to keep up with modern music tastes, but don't you worry, don't you worry child... see heaven's got RBRBand for YOU"
	
	[params.services.performance1]
	name=""
   	[[params.services.performance1.list]]
    name="Single track production"
   	[[params.services.performance1.list]]
   	name="Mixing"
   	[[params.services.performance1.list]]
   	name="Mastering" 



[[params.services]]
name = "Lyrics and Composition"
icon = "/img/music.png"
description = "At the loss of words after looking at our work? Well that happens, lucky for you we always have Lyrics for all occasions."
	
	[params.services.performance1]
	name=""
   	[[params.services.performance1.list]]
    name="Song writing"
   	[[params.services.performance1.list]]
   	name="Tune composition"
   	[[params.services.performance1.list]]
   	name="Arrangement"
   	[[params.services.performance1.list]]
   	name="Production"


[[params.services]]
name="Recording Studio"
icon = "/img/headphones.png"
description="Yes, we have a studio. Ok, a Home Studio, why else would we add 'Records' to our name? So fellow musicians, let's get that song off your list, which you've always dreamt of recording."
[[params.services.performance1.list]]
name="Multi-track recording"
[[params.services.performance1.list]]
name="Audio Mixing"






[[params.venues]]
name="Crowne Plaza"
source="img/CP.jpeg"

[[params.venues]]
name="Bayleaf Bistro"
source="img/bayleaf.jpg"

[[params.venues]]
name="South Avenue Mall"
source="img/SAM.png"

[[params.venues]]
name="The Great India Place Mall"
source="img/GIP.jpeg"

[[params.venues]]
name="BMC Software"
source="img/bmc.png"