baseurl = "http://example.org/"
languageCode = "en-us"
theme = "prologue"
title = "Prologue"
[params]
copyright = "Untitled."
description = "Vocalist, Sound Engineer"
name = "Prasang Misra"
[[params.portfolio1]]
alt = ""
source = "img/pic02.jpg"
title = "Ipsum Feugiat"
url = "#"
[[params.portfolio1]]
alt = ""
source = "img/pic03.jpg"
title = "Rhoncus Semper"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic04.jpg"
title = "Magna Nullam"
url = "#"
[[params.portfolio2]]
alt = ""
source = "img/pic05.jpg"
title = "Natoque Vitae"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic06.jpg"
title = "Dolor Penatibus"
url = "#"
[[params.portfolio3]]
alt = ""
source = "img/pic07.jpg"
title = "Orci Convallis"
url = "#"
[[params.social]]
icon = "twitter"
link = "https://twitter.com/prasangmisra"
medium = "twitter"
[[params.social]]
icon = "facebook"
link = "https://www.facebook.com/rbrbandrecords"
medium = "facebook"
[[params.social]]
icon = "youtube"
link = "https://www.youtube.com/channel/UCmS5QyYmLb1qLZAs_Kg97Bg"
medium = "youtube"
[[params.social]]
icon = "soundcloud"
link = "#"
medium = "soundcloud"
[[params.social]]
icon = "envelope"
link = "#"
medium = "email"
